# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Red-Gadget
tagline:          'A tech blog'
description:      'Technology changes everyday! We try to keep you posted on everything related to new technology.'
url:              http://dxartist.com
baseurl:          /

author:
  name:           'Sharath Kumar'
  url:            https://twitter.com/sharathdt

paginate:         5

# Custom vars
version:         1.0

github:
  repo:           https://github.com/sharathdt
